from sqlalchemy import Column, Float, Integer, String, Date, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from pydantic import BaseModel, EmailStr, Field
from typing import Optional, Optional, Any, List
from database import Base
from datetime import date, datetime
from models.stage_model import Stage
from models.status_model import Status
from models.user_model import User
from models.labtype_model import LabType
from models.province_model import Province
from models.district_model import District
from sqlalchemy.dialects.postgresql import JSONB

# ---------- SQLAlchemy Models ----------
class LaboratoryDB(Base):
    __tablename__ = "laboratorys"
    # a lab is identified by its code and registers one contact email
    __table_args__ = (
        UniqueConstraint("code", name="uq_laboratorys_code"),
        UniqueConstraint("email_address", name="uq_laboratorys_email_address"),
    )

    # id
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # name
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)

    # properties
    contact_person_name = Column(String, nullable=False)
    code = Column(String, nullable=False)
    lab_type_id = Column(Integer, ForeignKey("lab_types.id"), nullable=False)
    position = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    province_id = Column(Integer, ForeignKey("provinces.id"), nullable=False)
    email_address = Column(String, nullable=False)
    district_id = Column(Integer, ForeignKey("districts.id"), nullable=False)
    physical_address = Column(String, nullable=False)
    # method list
    method_list = Column(JSONB, nullable=False)
    # approval
    # user - null until an admin approves the registration and the lab account is created
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    # status
    status_id = Column(Integer, ForeignKey("list_statuses.id"), nullable=False)
    # stage
    stage_id = Column(Integer, ForeignKey("list_stages.id"), nullable=False)

    approval_levels = Column(Integer, nullable=False)

    review1_at = Column(DateTime(timezone=True), nullable=True)
    review1_by = Column(String, nullable=True)
    review1_comments = Column(String, nullable=True)

    review2_at = Column(DateTime(timezone=True), nullable=True)
    review2_by = Column(String, nullable=True)
    review2_comments = Column(String, nullable=True)

    review3_at = Column(DateTime(timezone=True), nullable=True)
    review3_by = Column(String, nullable=True)
    review3_comments = Column(String, nullable=True)

    # service columns
    created_at = Column(DateTime(timezone=True), default=datetime.now, nullable=True)
    created_by = Column(String, nullable=True)
    updated_at = Column(DateTime(timezone=True), onupdate=datetime.now, nullable=True)
    updated_by = Column(String, nullable=True)
    
    #relationships
    user = relationship("UserDB", back_populates="laboratories", foreign_keys=[user_id], lazy='raise')
    status = relationship("StatusDB", back_populates="laboratory", lazy='raise')
    stage = relationship("StageDB", back_populates="laboratory", lazy='raise')
    labtype = relationship("LabTypeDB", back_populates="laboratory", lazy='raise')
    province = relationship("ProvinceDB", back_populates="laboratory", lazy='raise')
    district = relationship("DistrictDB", back_populates="laboratory", lazy='raise')

    #links
    enrollment = relationship("EnrollmentDB", back_populates="laboratory", lazy='raise')
    applications = relationship("ApplicationsDB", back_populates="laboratory", lazy='raise')
    tbxpertultraresult = relationship("TBXpertUltraResultDB", back_populates="laboratory", lazy='raise')
    tbxpertxdrresult = relationship("TBXpertXDRResultDB", back_populates="laboratory", lazy='raise')
    hivvlresult = relationship("HIVVLResultDB", back_populates="laboratory", lazy='raise')
    hiveidresult = relationship("HIVEIDResultDB", back_populates="laboratory", lazy='raise')

# ---------- Pydantic Schemas ----------
class Laboratory(BaseModel):
    # id
    id: Optional[int] = None

    # name
    name: str = Field(
        ...,
        min_length=2,
        description="Name must be between at least 2 characters",
    )
    description: Optional[str] = None

    # properties
    contact_person_name: str = Field(
        ...,
        description="Contact Person Name must be provided",
    )
    code: Optional[str] = Field(
        default=None,
        description="Code is generated by the server on registration",
    )
    lab_type_id: int = Field(
        ...,
        description="Type of Lab must be provided",
    )
    position: str = Field(
        ...,
        description="Position must be provided",
    )
    phone_number: str = Field(
        ...,
        description="Phone Number must be provided",
    )
    province_id: int = Field(
        ...,
        description="Province must be provided",
    )
    email_address: str = Field(
        ...,
        description="Email Address must be provided",
    )
    district_id: int = Field(
        ...,
        description="District must be provided",
    )
    physical_address: str = Field(
        ...,
        description="Physical Address must be provided",
    )
    # method list
    method_list: list[dict[str, Any]]= Field(..., description="The EQA Scheme selection list must be provided")
    # approval
    # user
    user_id: Optional[int] = None

    # stage
    stage_id: int = Field(..., ge=1, le=8, description="Stage must be between 1 and 8")

    # status
    status_id: int = Field(
        ..., ge=1, description="Status must be greater than or equal to 1"
    )


    approval_levels: int = Field(
        ..., ge=1, le=3, description="Approval levels must be between 1 and 3"
    )

    review1_at: Optional[datetime] = None
    review1_by: Optional[str] = None
    review1_comments: Optional[str] = None

    review2_at: Optional[datetime] = None
    review2_by: Optional[str] = None
    review2_comments: Optional[str] = None

    review3_at: Optional[datetime] = None
    review3_by: Optional[str] = None
    review3_comments: Optional[str] = None

    # linkage
    created_at: Optional[datetime] = None
    created_by: Optional[str]  = None
    updated_at: Optional[datetime] = None
    updated_by: Optional[str] = None

    class Config:
        orm_mode = True     

class LaboratoryScheme(BaseModel):
    """One scheme a laboratory applied to, as vw_laboratory_scheme sees it"""

    scheme_id: int
    scheme_name: str
    provider_name: Optional[str] = None
    method_count: int = 0
    accepted_count: int = 0
    pending_count: int = 0
    rejected_count: int = 0
    method_names: Optional[str] = None
    accepted_method_names: Optional[str] = None
    # Accepted, Pending or Rejected
    participation: Optional[str] = None

    class Config:
        orm_mode = True


class LaboratoryWithDetail(Laboratory):
    stage: Stage
    status: Status
    # a lab that registered itself has no owning user until it is approved
    user: Optional[User] = None

    labtype: LabType
    province: Province
    district: District


class LaboratoryWithSchemes(LaboratoryWithDetail):
    """A laboratory and the schemes it applied to.

    Kept apart from `LaboratoryWithDetail` so the plain laboratory listing
    stays exactly what it was - the scheme summary costs a second query and a
    good deal of payload, and only the pages that show it should pay for it.
    """

    # which schemes the lab applied to, and how each stands. Empty for a
    # registration nobody has reviewed yet.
    scheme_list: Optional[List[LaboratoryScheme]] = []
    # every scheme in scheme_list as one string. This is what a listing filters
    # and searches on, so the filter matches what the column actually shows -
    # including a scheme the lab applied to but was not accepted for.
    scheme_names: Optional[str] = None
    scheme_count: Optional[int] = 0
    # the narrower answer: the schemes the lab is actually registered in
    accepted_scheme_names: Optional[str] = None
    accepted_scheme_count: Optional[int] = 0

class ParamLaboratoryEdit(BaseModel):
    # the one-laboratory page shows its schemes, so it gets the fuller model
    laboratory: Optional[LaboratoryWithSchemes] = None
    labtypeList: Optional[List[LabType]] = []
    provinceList: Optional[List[Province]] = []
    districtList: Optional[List[District]] = []

    class Config:
        orm_mode = True

class SignupMethod(BaseModel):
    """One method a registering lab says it provides."""

    id: int = Field(..., ge=1, description="Method must be provided")


class ParamLaboratorySignup(BaseModel):
    """Posted by a laboratory registering itself for EQA.

    Deliberately narrower than `Laboratory`: a self-registering lab may not
    choose its own approval state, owning user or role. The server decides
    those, and only ever grants a laboratory role.
    """

    # name
    name: str = Field(..., min_length=2, description="Name must be provided")
    description: Optional[str] = None

    # properties
    contact_person_name: str = Field(
        ..., min_length=2, description="Contact Person Name must be provided"
    )
    lab_type_id: int = Field(..., ge=1, description="Type of Lab must be provided")
    position: str = Field(..., min_length=2, description="Position must be provided")
    phone_number: str = Field(
        ..., min_length=6, max_length=20, description="Phone Number must be provided"
    )
    province_id: int = Field(..., ge=1, description="Province must be provided")
    email_address: EmailStr
    district_id: int = Field(..., ge=1, description="District must be provided")
    physical_address: str = Field(
        ..., min_length=2, description="Physical Address must be provided"
    )

    # the methods the lab is applying to take part in
    method_list: List[SignupMethod] = Field(
        ..., min_items=1, description="At least one method must be selected"
    )


class LaboratorySignupResult(BaseModel):
    """What a lab gets back after registering."""

    succeeded: bool
    message: str
    laboratory_id: int
    code: str
    application_count: int
